name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Project Dependencies
        run: pnpm i

      - name: Linting & Checking types for project
        run: |
          pnpm run lint
          pnpm run check-types

  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 18.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Project Dependencies
        run: pnpm i

      - name: Linting & Checking types for project
        run: |
          pnpm run lint
          pnpm run check-types
